### ISSUE TITLE
dist folder doesn't appear after compilation

### ISSUE THREAD

**Issue by euklad** [tonysneed/Demo.VSCode.TypeScript#2]
I just installed VS code this morning and  followed steps in readme.md file.
I tried to get project from git and tried to use yo tonysneed-vscode-typescript and result is the same.
When I start compilation in VS Code I see output:
[15:48:49] Using gulpfile c:\Projects\tsp2\gulpfile.js
[15:48:49] Starting 'vet:typescript'...
[15:48:49] Analyzing typescript code with TSLint
[15:48:50] Starting 'clean:generated'...
[15:48:50] Cleaning generated files: ./dist/
[15:48:50] Finished 'clean:generated' after 20 ms
[15:48:51] Finished 'vet:typescript' after 2.98 s
[15:48:51] Starting 'typescript-compile'...
[15:48:51] Compiling TypeScript
[15:48:52] Finished 'typescript-compile' after 17 ms
however there is no dist folder in the project root folder.
As result when I try to debug I see the error "Attribute 'outDir' does not exist ('c:\Projects\tsp2/dist')."

One more interesting thing - when I add some syntax error typing in greeter.ts file the compilation fails:
[16:02:01] Using gulpfile c:\Projects\tsp2\gulpfile.js
[16:02:01] Starting 'vet:typescript'...
[16:02:01] Analyzing typescript code with TSLint
[16:02:01] Starting 'clean:generated'...
[16:02:01] Cleaning generated files: ./dist/
[16:02:01] Finished 'clean:generated' after 8.16 ms
c:\Projects\tsp2\src\greeter\greeter.ts
      line 4  col 8  missing semicolon
    × 1 error
[16:02:01] Finished 'vet:typescript' after 380 ms
[16:02:01] Starting 'typescript-compile'...
[16:02:01] Compiling TypeScript
[16:02:01] Finished 'typescript-compile' after 9.58 ms

but when I fix it removing syntax error and compile - dist folder doesn't appear.

**Comment by tonysneed** [comment]
I just ran the build task, and the dist folder is created on my system.  Try performing the following steps.

First run `npm install` to make sure all the dependencies have been satisfied.

Then, check the that the contents of your **tsconfig.json** file are as follows:

``` json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "declaration": true,
        "removeComments": true,
        "noImplicitAny": true,
        "rootDir": ".",
        "outDir": "../dist"
    },
    "exclude": [
        "node_modules"
    ]
}
```

Delete the **dist** directory if it exists, and execute the following from the command line at the root directory:

```
node_modules/typescript/bin/tsc -p src
```

You should see the **dist** directory magically appear, and it should contain the js output files.

**Comment by euklad** [comment]
may be something wrong with my nodejs.
I work on Windows 10 and when I run in cmd line "node_modules\typescript\bin\tsc -p src" it says:  'node_modules\typescript\bin\tsc' is not recognized as an internal or external command,
operable program or batch file.
How ever "npm install" works fine with some warnings though.

**Comment by euklad** [comment]
definitely the command "node_modules/typescript/bin/tsc -p src" doesn't work in my environment.
When I updated compile task a bit it started working:

gulp.task('typescript-compile', ['vet:typescript', 'clean:generated'], function () {

```
log('Compiling TypeScript');
exec('node_modules/typescript/bin/tsc -p src');

// var tsResult = gulp.src(config.ts.src)
//                 .pipe(ts(config.root));

var tsResult = gulp.src('./src/**/*.ts')
                   .pipe(sourcemaps.init())
                   .pipe(ts(tsProject));

tsResult.dts.pipe(gulp.dest(config.js.dir));
return tsResult.js
                .pipe(sourcemaps.write('.'))
                .pipe(gulp.dest(config.js.dir));
```

});

**Comment by euklad** [comment]
the command "node_modules.bin\tsc  -p src" works all right

**Comment by tonysneed** [comment]
The problem with using `gulp-typescript` is that it will not preserve directory structure for source maps, so debugging may not work for you with this approach.  Instead, you can install typescript globally and change the exec to use it.

**Comment by tonysneed** [comment]
Just saw you last comment that you were able to change the path to tsc to get it working. 👍

**Comment by Halltech176** [comment]
dist folders fails to appear during compilation but the typescript code is running file without an error in my nodejs application, hope the absence of the dist folder will not cause any bad side effect
